---
title: "Run PhyloNOW"
---

```{r setup, include=FALSE}
# create output directories
outdir_fasta <- file.path(currentdir, "fasta")
outdir_split <- file.path(currentdir, "split")
outdir_merge <- file.path(currentdir, "merge")
outdir_final <- file.path(currentdir, "final")
sapply(c(outdir_fasta, outdir_split, outdir_merge, outdir_final), function(x) {
  if (!dir.exists(x)) { dir.create(x, recursive=T) }})

# output summary files
fn_aicsum <- file.path(currentdir, paste0(params$prefix, ".aicsum"))
fn_winsum <- file.path(currentdir, paste0(params$prefix, ".winsum"))
fn_topsum <- file.path(currentdir, paste0(params$prefix, ".topsum"))
fn_rootstrap <- file.path(currentdir, paste0(params$prefix, ".rootstrap"))
fn_midroot <- file.path(currentdir, paste0(params$prefix, ".midroot"))

fn_uqtops_all <- file.path(currentdir, paste0(params$prefix, "_all.uqtops"))
fn_uqtops_highbs <- file.path(currentdir, paste0(params$prefix, "_highbs.uqtops"))

# set minimum bootstrap value to be considered high
min_branch_support <- 80
if (tolower(params$bootstrap_type) == "ufboot") {
  min_branch_support <- 95
}
```

```{r window-aln, include=FALSE}
readr::write_lines(c("", "---------- Window Alignment --------"), path=fn_log, append=T)

# disable scientific notation 
options(scipen=999)

# read FASTA file
seq <- Biostrings::readBStringSet(params$input_aln)
names(seq) <- gsub(" ", "", names(seq))

# check if FASTA file is MSA
seq_len <- Biostrings::width(seq)
if (length(unique(seq_len)) != 1) {
  log4r::error(fn_logger, "Input alignment is not a MSA. Exited.")
  stop("Input alignment is not a MSA. Exited.")
}

# retrieve the sequence length
seq_len <- seq_len[1]

# extract the initial window size
init_wsize <- params$init_wsize
if (is.na(init_wsize)) {
  init_wsize <- seq_len
}

# set outgroup
outgroup <- params$outgroup
if (any(outgroup != "")) {
  outgroup <- names(seq)[names(seq)%in%outgroup]
}

msg <- paste0("Running PhyloNOW with a starting window size of ", init_wsize, "bp")
readr::write_lines(msg, path=fn_log, append=T)
cat(msg)

# generate data.frame for each window
numw <- ceiling(seq_len/init_wsize)
df_windows <- f_create_perwindow_df(numw, seq_len, init_wsize)

# create doSNOW cluster
n_thread <- ifelse(params$thread<=nrow(df_windows), params$thread, nrow(df_windows))

nwcl <- makeCluster(n_thread)
doSNOW::registerDoSNOW(nwcl)

# generate window alignments and trees
foreach (i = 1:nrow(df_windows)) %dopar% {
  # output directory
  temp_dir_output <- file.path(outdir_fasta, df_windows$window_name[i])
  if (!dir.exists(temp_dir_output)) {
    dir.create(temp_dir_output, recursive=T)
  }

  # output files
  temp_fn_fasta <- file.path(temp_dir_output, paste0(df_windows$window_name[i], ".fa"))
  temp_fn_iqtree <- file.path(temp_dir_output, paste0(df_windows$window_name[i], ".fa.iqtree"))

  # create window alignment
  if (!file.exists(temp_fn_fasta) || params$redo) {
    f_extract_window(outdir=temp_dir_output,
                     seq=seq,
                     window_name=df_windows$window_name[i],
                     start=df_windows$start[i],
                     end=df_windows$end[i])
  }

  # run IQ-TREE2
  if (!file.exists(temp_fn_iqtree) || params$redo) {
    f_iqtree2_single(input=temp_fn_fasta, 
                     outgroup="",
                     window_size=df_windows$length[i],
                     setblmin=params$set_blmin,
                     setmodel=params$set_model,
                     substitution_model=params$substitution_model,
                     bootstrap_type="",
                     bootstrap_n=0,
                     exe_iqtree2=params$exe_iqtree)
  }
}
  
stopCluster(nwcl)
```

```{r, include=FALSE}
# disable scientific notation 
options(scipen=999)

# create doSNOW cluster
nwcl <- makeCluster(n_thread)
doSNOW::registerDoSNOW(nwcl)

# output file
df_current <- NULL
fn_df_current <- file.path(outdir_split, "summary_iter00.tsv")

# calculate the AIC of the initial window(s)
if (file.exists(fn_df_current) && !params$redo) {
  df_current <- data.table::fread(fn_df_current)

} else {
  # retrieve the AIC per window
  df_current <- foreach (window=df_windows$window_name, .combine='rbind') %dopar% {
    # input files
    fn_fasta <- file.path(outdir_fasta, window, paste0(window, ".fa"))
    fn_iqtree <- file.path(outdir_fasta, window, paste0(window, ".fa.iqtree"))

    # calculate AIC
    aic <- ifelse (!file.exists(fn_iqtree), NA, f_extract_tree_aic(fn_iqtree)) 

    # read FASTA
    seq <- Biostrings::readBStringSet(fn_fasta)

    # update data.table
    return(data.table::data.table(iter="00", window=window, length=Biostrings::width(seq)[1], aic=aic, dir=fn_fasta, is_split=TRUE))
  }

  # save output data.table
  data.table::fwrite(df_current, file=fn_df_current, row.names=F, col.names=T, quote=F, sep="\t")
}

stopCluster(nwcl)

# store the initial AIC
df_aic <- data.table::data.table(step="initial", iter="00", aic=sum(df_current$aic, na.rm=TRUE))

# print the total AIC
msg <- paste("Total AIC of initial alignment:", sum(df_current$aic, na.rm=TRUE))
log4r::info(fn_logger, msg)
cat(msg)
```

```{r split}
readr::write_lines(c("", "----------      Split      ---------",
                         paste("Minimum number of informative sites:", params$min_informative_sites)),
                         path=fn_log, append=T)

# set initial variables
iterator <- 0
is_repeat <- TRUE

# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

# set initial length
init_wlen <- df_current$length[1]

# iterate over windows
while (is_repeat == TRUE) {
  # stop the iteration if all windows are not divisible
  if (all(df_current$is_split == FALSE)) {
    is_repeat <- FALSE
    break
  }

  # update iterator
  iterator <- iterator + 1
  iterator_padded <- paste0(formatC(iterator, width=2, format="d", flag="0"))
  iterator_padded_id <- paste0("s", iterator_padded)

  # output file
  split_iter_summary <- paste0("summary_iter", iterator_padded, ".tsv")
  fn_df_current <- file.path(outdir_split, split_iter_summary)

  if (file.exists(fn_df_current) && !params$redo) {
    df_current <- data.table::fread(fn_df_current)

    # print the total AIC
    msg <- paste0("Total AIC after split iteration ", iterator_padded, ": ", sum(df_current$aic, na.rm=TRUE))
    log4r::info(fn_logger, msg)
    cat(msg)

    # update the AIC data.frame
    df_aic <- rbind(df_aic, data.table::data.table(step="split", iter=iterator_padded_id, aic=sum(df_current$aic, na.rm=TRUE)))
    
    # move to the next iteration
    next
  }

  # iterate over windows
  df_output <- foreach (i=1:nrow(df_current), .combine='rbind') %dopar% {
    require(dplyr)

    # skip the window if not divisible
    if (!df_current$is_split[i] || is.na(df_current$aic[i])) {
      return(data.table::data.table(iter=df_current$iter[i],
                                    window=df_current$window[i],
                                    length=df_current$length[i],
                                    aic=df_current$aic[i],
                                    dir=df_current$dir[i],
                                    is_split=FALSE))
    }

    # output directory
    dir_output <- file.path(outdir_split, paste0("iter", iterator_padded), df_current$window[i])
    if (!dir.exists(dir_output)) {
      dir.create(dir_output, recursive=T)
    }

    # output file
    df_prop <- data.table::data.table(prop=character(), window_one=character(), window_two=character(),
                                                        length_one=numeric(), length_two=numeric(),
                                                        aic_one=numeric(), aic_two=numeric(),
                                                        dir_one=character(), dir_two=character())
    fn_output <- file.path(dir_output, "aic_table.tsv")

    if (file.exists(fn_output) && !params$redo) {
      df_prop <- data.table::fread(fn_output)

      if (nrow(df_prop) == 0) {
        return(data.table::data.table(iter=df_current$iter[i],
                                      window=df_current$window[i],
                                      length=df_current$length[i],
                                      aic=df_current$aic[i],
                                      dir=df_current$dir[i],
                                      is_split=FALSE))
      }

    } else {
      # read FASTA
      seq <- Biostrings::readBStringSet(df_current$dir[i])
      seq_len <- Biostrings::width(seq)[1]

      # extract AIC
      for (prop in params$split_prop) {
        window_one <- paste0(df_current$window[i], "_", gsub("\\.","",prop), "_1")
        window_two <- paste0(df_current$window[i], "_", gsub("\\.","",prop), "_2")

        # extract the alignment
        midpoint <- ceiling(prop*seq_len)
        f_extract_window(dir_output, seq, window_one, 1, midpoint)
        f_extract_window(dir_output, seq, window_two, midpoint+1, seq_len)

        # check the maximum bound of -blmin
        seq_len_one <- midpoint
        seq_len_two <- seq_len - midpoint
        if (1/seq_len_one >= 0.1 || 1/seq_len_two >= 0.1) {
          next
        }

        # run IQ-TREE2
        fn_fasta_one <- file.path(dir_output, paste0(window_one, ".fa"))
        fn_fasta_two <- file.path(dir_output, paste0(window_two, ".fa"))
        f_iqtree2_single(fn_fasta_one, "", seq_len_one, params$set_blmin, params$set_model, params$substitution_model, "", 0, params$exe_iqtree)
        f_iqtree2_single(fn_fasta_two, "", seq_len_two, params$set_blmin, params$set_model, params$substitution_model, "", 0, params$exe_iqtree)

        # extract AIC from IQ-TREE output files
        fn_iqtree_one <- paste0(fn_fasta_one, ".iqtree")
        fn_iqtree_two <- paste0(fn_fasta_two, ".iqtree")
        if (!all(file.exists(fn_iqtree_one, fn_iqtree_two))) {
          next
        }

        # check informative sites
        if (!f_is_informative(fn_iqtree_one, params$min_informative_sites) || !f_is_informative(fn_iqtree_two, params$min_informative_sites)) {
          next
        }

        # extract AIC for each window
        aic_one <- f_extract_tree_aic(fn_iqtree_one)
        aic_two <- f_extract_tree_aic(fn_iqtree_two)

        # update data.frame
        df_prop <- rbind(df_prop, data.table::data.table(prop=prop, window_one=window_one, window_two=window_two,
                                                                    length_one=seq_len_one, length_two=seq_len_two,
                                                                    aic_one=aic_one, aic_two=aic_two,
                                                                    dir_one=fn_fasta_one, dir_two=fn_fasta_two))
      }

      # save data.frame
      data.table::fwrite(df_prop, file=fn_output, quote=F, row.names=F, col.names=T, sep="\t")
    }

    # extract the best AIC score
    if (nrow(df_prop) == 0) {
      return(data.table::data.table(iter=df_current$iter[i],
                                    window=df_current$window[i],
                                    length=df_current$length[i],
                                    aic=df_current$aic[i],
                                    dir=df_current$dir[i],
                                    is_split=FALSE))
    }

    df_output_min_aic <- df_prop %>% mutate(sum_aic=aic_one+aic_two) %>% filter(sum_aic==min(sum_aic))
    if (df_output_min_aic$sum_aic[1] < df_current$aic[i]) {
      return(rbind(data.table::data.table(iter=iterator_padded_id,
                                          window=df_output_min_aic$window_one[1],
                                          length=df_output_min_aic$length_one[1],
                                          aic=df_output_min_aic$aic_one[1],
                                          dir=df_output_min_aic$dir_one[1],
                                          is_split=TRUE),
                   data.table::data.table(iter=iterator_padded_id,
                                          window=df_output_min_aic$window_two[1],
                                          length=df_output_min_aic$length_two[1],
                                          aic=df_output_min_aic$aic_two[1],
                                          dir=df_output_min_aic$dir_two[1],
                                          is_split=TRUE)))
    } else {
      return(data.table::data.table(iter=df_current$iter[i],
                                         window=df_current$window[i],
                                         length=df_current$length[i],
                                         aic=df_current$aic[i],
                                         dir=df_current$dir[i],
                                         is_split=FALSE))
    }
  }

  # update variables
  df_current <- as.data.frame(df_output)
  df_current$basewindow <- sapply(df_current$window, function(x) { paste(unlist(strsplit(x, split="_"))[1:2], collapse="_") })
  df_current <- df_current %>%
                  group_by(basewindow) %>%
                  mutate(freq=formatC(row_number(), width=2, format="d", flag="0")) %>%
                  ungroup() %>%
                  mutate(window=paste(basewindow, freq, sep="_")) %>%
                  select(-basewindow, -freq)

  # save output file
  data.table::fwrite(df_current, file=fn_df_current, row.names=F, col.names=T, quote=F, sep="\t")

  # print the total AIC
  msg <- paste0("Total AIC after split iteration ", iterator_padded, ": ", sum(df_current$aic, na.rm=TRUE))
  log4r::info(fn_logger, msg)
  cat(msg)

  # update the AIC data.frame
  df_aic <- rbind(df_aic, data.table::data.table(step="split", iter=iterator_padded_id, aic=sum(df_current$aic, na.rm=TRUE)))

  rm(df_output)
}

stopCluster(nwcl)

# remove column from the table
df_current$is_split <- NULL
```

```{r merge}
readr::write_lines(c("","-----------       Merge     ---------"), path=fn_log, append=T)

# disable scientific notation 
options(scipen=999)

# add new columns to the table
df_current$is_merged <- TRUE

# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

# set initial values
is_repeat <- TRUE
iterator <- 0

# iterate over windows
while (is_repeat == TRUE) {
  # stop the iteration if none of the windows is newly merged
  if (all(df_current$is_merged == FALSE)) {
    is_repeat <- FALSE
    break
  }

  # update iterator
  iterator <- iterator + 1
  iterator_padded <- paste0(formatC(iterator, width=2, format="d", flag="0"))
  iterator_padded_id <- paste0("m", iterator_padded)

  # output file
  merge_iter_summary <- paste0("summary_iter", iterator_padded, ".tsv")
  fn_df_current <- file.path(outdir_merge, merge_iter_summary)
  if (file.exists(fn_df_current) && !params$redo) {
    df_current <- data.table::fread(fn_df_current)

    # print the total AIC
    msg <- paste0("Total AIC after merge iteration ", iterator_padded, ": ", sum(df_current$aic, na.rm=TRUE))
    log4r::info(fn_logger, msg)
    cat(msg)

    # update the AIC data.frame
    df_aic <- rbind(df_aic, data.table::data.table(step="merge", iter=iterator_padded_id, aic=sum(df_current$aic, na.rm=TRUE)))

    # move to the next iteration
    next
  }

  # create all neighbouring windows
  df_merge_now <- foreach(i=1:nrow(df_current), .combine='rbind') %dopar% {
    df_temp <- NULL

    # store window pairs
    if (df_current$is_merged[i] && !is.na(df_current$aic[i])) {
      if (i != nrow(df_current) && !is.na(df_current$aic[i+1])) {
        wmerge <- paste0(df_current$window[i], "x", gsub("window_","",df_current$window[i+1]))
        df_temp <- rbind(df_temp, data.table::data.table(window_one=df_current$window[i], window_two=df_current$window[i+1],
                                                         aic_one=df_current$aic[i], aic_two=df_current$aic[i+1],
                                                         dir_one=df_current$dir[i], dir_two=df_current$dir[i+1], window_merge=wmerge))
      }
      
      if (i != 1 && !is.na(df_current$aic[i-1])) {
        wmerge <- paste0(df_current$window[i-1], "x", gsub("window_","",df_current$window[i]))
        df_temp <- rbind(df_temp, data.table::data.table(window_one=df_current$window[i-1], window_two=df_current$window[i],
                                                        aic_one=df_current$aic[i-1], aic_two=df_current$aic[i],
                                                        dir_one=df_current$dir[i-1], dir_two=df_current$dir[i], window_merge=wmerge))
        
      }
    }

    return(df_temp)
  }

  # remove duplicated entry
  df_merge_now <- unique(df_merge_now)

  # iterate over windows that can be merged
  df_output <- NULL
  fn_output <- file.path(outdir_merge, paste0("iter", iterator_padded), "aic_table.tsv")

  if (file.exists(fn_output) && !params$redo) {
    df_output <- data.table::fread(fn_output)
  
  } else {
    df_output <- foreach (i=1:nrow(df_merge_now), .combine='rbind') %dopar% {
      # output directory
      dir_output_iter <- file.path(outdir_merge, paste0("iter", iterator_padded), df_merge_now$window_one[i])
      if (!dir.exists(dir_output_iter)) {
        dir.create(dir_output_iter, recursive=T)
      }

      # output file
      fn_merged_fasta <- file.path(dir_output_iter, paste0(df_merge_now$window_one[i], "_", df_merge_now$window_two[i], ".fa"))
      if (!file.exists(fn_merged_fasta) || params$redo) {
        # merge sequence
        system(paste(params$exe_seqkit, "concat --full", df_merge_now$dir_one[i], df_merge_now$dir_two[i], ">", fn_merged_fasta))
      }

      # read FASTA file
      seq <- Biostrings::readBStringSet(fn_merged_fasta)
      seq_len <- Biostrings::width(seq)[1]

      # output files
      fn_iqtree <- paste0(fn_merged_fasta, ".iqtree")
      if (!file.exists(fn_iqtree) || params$redo) {
        f_iqtree2_single(fn_merged_fasta, "", seq_len, params$set_blmin, params$set_model, params$substitution_model, "", 0, params$exe_iqtree)
      }

      # extract AIC
      aic <- f_extract_tree_aic(fn_iqtree)

      # initial AIC
      init_aic <- df_merge_now$aic_one[i] + df_merge_now$aic_two[i]

      return(data.table::data.table(window_one=df_merge_now$window_one[i], window_two=df_merge_now$window_two[i],
                                    aic_one=df_merge_now$aic_one[i], aic_two=df_merge_now$aic_two[i],
                                    dir_one=df_merge_now$dir_one[i], dir_two=df_merge_now$dir_two[i],
                                    window_merge=df_merge_now$window_merge[i], aic_merge=aic, delta_aic=aic-init_aic,
                                    dir_merge=fn_merged_fasta, length_merge=seq_len))
    }

    # sort the AIC from the lowest
    df_output <- df_output %>% arrange(delta_aic)
    data.table::fwrite(df_output, file=fn_output, row.names=F, col.names=T, quote=F, sep="\t")
  }

  # set all is_merged to FALSE
  df_current$is_merged <- FALSE
  df_output <- df_output %>% filter(delta_aic < 0)

  # check if data.frame has zero row
  if (nrow(df_output) != 0) {
    # extract merged windows with the biggest AIC improvement and update df_current
    for (i in 1:nrow(df_output)) {
      # extract row
      id_row <- match(df_output$window_one[i], df_current$window)

      # check if combination is invalid
      if (is.na(id_row) || df_output$window_two[i] != df_current$window[id_row+1]) {
        next
      }

      # update the row
      df_current[id_row,] <- list(iter=iterator_padded_id,
                                  window=df_output$window_merge[i],
                                  length=df_output$length_merge[i],
                                  aic=df_output$aic_merge[i],
                                  dir=df_output$dir_merge[i],
                                  is_merged=TRUE)
      df_current <- df_current[-(id_row+1),]
    }
  }

  # update variables
  df_current$basewindow <- sapply(df_current$window, function(x) { paste(unlist(strsplit(x, split="_"))[1:2], collapse="_") })
  df_current <- df_current %>%
                  group_by(basewindow) %>%
                  mutate(freq=formatC(row_number(), width=2, format="d", flag="0")) %>%
                  ungroup() %>%
                  mutate(window=paste(basewindow, freq, sep="_")) %>%
                  select(-basewindow, -freq) 

  # save output file
  data.table::fwrite(df_current, file=fn_df_current, row.names=F, col.names=T, quote=F, sep="\t")
  
  # print the total AIC
  msg <- paste0("Total AIC after merge iteration ", iterator_padded, ": ", sum(df_current$aic, na.rm=TRUE))
  log4r::info(fn_logger, msg)
  cat(msg)

  # update the AIC data.frame
  df_aic <- rbind(df_aic, data.table::data.table(step="merge", iter=iterator_padded_id, aic=sum(df_current$aic, na.rm=TRUE)))

  rm(df_output)
}

stopCluster(nwcl)

# save data.frame
df_current$is_merged <- NULL
data.table::fwrite(df_aic, file=fn_aicsum, row.names=F, col.names=T, quote=F, sep="\t")
data.table::fwrite(df_current, file=fn_winsum, row.names=F, col.names=T, quote=F, sep="\t")

# print the final total AIC
msg <- paste("Final total AIC:", sum(df_current$aic, na.rm=TRUE))
log4r::info(fn_logger, msg)
cat(msg)
```

## Plot of total AIC changes across iterations
```{r, out.width="100%", echo=FALSE}
# create a sequential x-axis
df_aic$x <- 1:nrow(df_aic)

# visualisation
ggplot(df_aic, aes(x=x, y=aic, colour=type, group=1)) +
  geom_line(color="grey70", linewidth=1.2) +
  geom_point(size=4) +
  scale_x_continuous(breaks=df_aic$x, labels=df_aic$iter) +
  scale_color_manual(values=c(init="black", split="#378ADD", merge="#1D9E75")) +
  labs(x="Step", y="AIC", color="Analysis") +
  theme_minimal(base_size=16)
```

```{r tree}
readr::write_lines(c("","-----------    Gene Trees   ---------"), path=fn_log, append=T)

# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

# iterate over windows
df_topology <- foreach (i = 1:nrow(df_current), .combine='rbind') %dopar% {
  # output directory
  outdir_window <- file.path(outdir_final, df_current$window[i])
  if (!dir.exists(outdir_window)) {
    dir.create(outdir_window, recursive=T)
  }

  # output files
  fn_fasta <- file.path(outdir_window, paste0(df_current$window[i], ".fa"))
  fn_iqtree <- paste0(fn_fasta, ".iqtree")
  fn_treefile <- paste0(fn_fasta, ".treefile")
  if (!all(file.exists(fn_fasta, fn_iqtree, fn_treefile)) || params$redo) {
    system(paste("cp", df_current$dir[i], fn_fasta))

    # read FASTA file
    seq <- Biostrings::readBStringSet(fn_fasta)

    # conditional if bootstrap is needed
    if (length(unique(as.character(seq))) <= 3) {
      f_iqtree2_single(fn_fasta, outgroup, df_current$length[i], params$set_blmin, params$set_model, params$substitution_model, "", 0, params$exe_iqtree)
    } else {
      f_iqtree2_single(fn_fasta, outgroup, df_current$length[i], params$set_blmin, params$set_model, params$substitution_model, params$bootstrap_type, params$bootstrap, params$exe_iqtree)
    }
  }

  # check if .treefile is not available
  if (!file.exists(fn_treefile)) {
    return(data.table::data.table(window=df_current$window[i], length=df_current$length[i], topology=NA, is_highbs=FALSE))
  }

  # extract topology
  tre <- ape::read.tree(fn_treefile)
  tre$edge.length <- NULL
  tre$node.label <- NULL

  # check if gene tree has high average bootstrap value
  is_highbs <- f_is_tree_highbs(fn_treefile, params$bootstrap_type, min_branch_support)

  return(data.table::data.table(window=df_current$window[i], length=df_current$length[i], topology=ape::write.tree(tre), is_highbs=is_highbs))
}

stopCluster(nwcl)

# update list of topologies
if (all(outgroup != "") && length(outgroup) != 0) {
  df_topology <- f_update_df_topology_rooted(df_topology)
} else {
  df_topology <- f_update_df_topology_unrooted(df_topology)
}

# save data.frame
data.table::fwrite(df_topology, file=fn_topsum, row.names=F, col.names=T, quote=F, sep="\t")

# summarise topology proportion
df_topology_all <- df_topology %>%
    group_by(topology) %>%
    summarise(sum_freq=n(), sum_length=sum(length)) %>%
    arrange(desc(sum_freq), desc(sum_length)) %>%
    mutate(prop=round(sum_freq/sum(sum_freq)*100,3), w_prop=round(sum_length/sum(sum_length)*100,3))
data.table::fwrite(df_topology_all, file=fn_uqtops_all, row.names=F, col.names=T, quote=F, sep="\t")

# summarise highly-supported topology proportion
if (all(outgroup != "") && length(outgroup) != 0) {
  df_topology_highbs <- df_topology %>%
      filter(is_highbs==TRUE) %>%
      group_by(topology) %>%
      summarise(sum_freq=n(), sum_length=sum(length)) %>%
      arrange(desc(sum_freq), desc(sum_length)) %>%
      mutate(prop=round(sum_freq/sum(sum_freq)*100,3), w_prop=round(sum_length/sum(sum_length)*100,3))
  data.table::fwrite(df_topology_highbs, file=fn_uqtops_highbs, row.names=F, col.names=T, quote=F, sep="\t")
}
```

```{r tree-rootstrap, eval=params$run_rootstrap}
# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

# iterate over windows
df_rootstrap <- foreach (i = 1:nrow(df_current), .combine='rbind') %dopar% {
  # output directory
  outdir_window <- paste0(outdir_final, df_current$window[i], "/")

  # input file
  fn_fasta <- paste0(outdir_window, df_current$window[i], ".fa")

  # output files
  prefix <- paste0(outdir_window, "nonrev_", df_current$window[i])
  fn_rootstrap_nexus <- paste0(prefix, ".rootstrap.nex")
  fn_treefile <- paste0(prefix, ".treefile")
  if (!all(file.exists(fn_rootstrap_nexus, fn_treefile)) || params$redo) {
    # run rootstrap
    f_calculate_rootstrap(fn_fasta, prefix, params$bootstrap_type, params$bootstrap, params$exe_iqtree)
  }

  # check if .treefile is not available
  if (!all(file.exists(fn_rootstrap_nexus, fn_treefile))) {
    return(data.table::data.table(window=df_current$window[i], length=df_current$length[i], topology=NA, rootstrap=NA))
  }

  # extract topology
  tre <- ape::read.tree(fn_treefile)
  tre$edge.length <- NULL
  tre$node.label <- NULL

  max_root <- f_extract_max_rootstrap(fn_rootstrap_nexus)

  return(data.table::data.table(window=df_current$window[i], length=df_current$length[i], topology=ape::write.tree(tre), rootstrap=max_root))
}

stopCluster(nwcl)

# update list of topologies
df_rootstrap <- f_update_df_topology_rooted(df_rootstrap)

# save data.frame
data.table::fwrite(df_rootstrap, file=fn_rootstrap, row.names=F, col.names=T, quote=F, sep="\t")
```

```{r tree-midroot, eval=params$run_midpoint_root}
# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

# iterate over windows
df_midroot <- foreach (i = 1:nrow(df_current), .combine='rbind') %dopar% {
  # output directory
  outdir_window <- paste0(outdir_final, df_current$window[i], "/")

  # input file
  fn_treefile <- paste0(outdir_window, df_current$window[i], ".fa.treefile")

  # output files
  fn_treefile_root <- paste0(outdir_window, "midroot_", df_current$window[i], ".treefile")
  if (!file.exists(fn_treefile_root) || params$redo) {
    # midpoint root
    tre <- ape::read.tree(fn_treefile)
    tre_root <- phangorn::midpoint(tre)
    ape::write.tree(tre_root, file=fn_treefile_root)
  }

  # check if .treefile is not available
  if (!file.exists(fn_treefile_root)) {
    return(data.table::data.table(window=df_current$window[i], length=df_current$length[i], tree=NA, topology=NA))
  }

  # extract topology
  tre_root <- ape::read.tree(fn_treefile_root)
  top_root <- ape::read.tree(fn_treefile_root)
  top_root$edge.length <- NULL
  top_root$node.label <- NULL

  return(data.table::data.table(window=df_current$window[i], length=df_current$length[i], tree=ape::write.tree(tre_root), topology=ape::write.tree(top_root)))
}

stopCluster(nwcl)

# update list of topologies
df_midroot <- f_update_df_topology_rooted(df_midroot)

# save data.frame
data.table::fwrite(df_midroot, file=fn_midroot, row.names=F, col.names=T, quote=F, sep="\t")
```
